

# ================================ INFORMATIONS =============================================
informations:
  version: 1.0.0
# =================================== STEPS =================================================
program_steps:
  download_data: False
  insert_data: False
  plot_graph: True
# ================================== OPTIONS ================================================
options:
  pages_per_category: 2
  word_per_page: 20
  waiting_time: 1
# =================================== GRAPH =================================================
graph:
  width: 25
  height: 25
  dpi: 150
  node_size: 2000
  node_color: red
  node_text_size: 20
  edge_color: black
